parameters:
    liip_imagine.controller.class: 'Genj\ThumbnailBundle\Controller\ImagineController'
    liip_imagine.cache.manager.class: 'Genj\ThumbnailBundle\Imagine\Cache\CacheManager'
    liip_imagine.cache.resolver.web_path.class: 'Genj\ThumbnailBundle\Imagine\Cache\Resolver\WebPathResolver'

services:

    # this service is an override of the definition in the LiipImagineBundle
    liip_imagine.cache.manager:
        class: '%liip_imagine.cache.manager.class%'
        arguments:
            - '@liip_imagine.filter.configuration'
            - '@router'
            - '@liip_imagine.cache.signer'
            - '@event_dispatcher'
            - '%liip_imagine.cache.resolver.default%'
        calls:
            - ['setContainer', ['@service_container']]
    # this service is an override of the definition in the LiipImagineBundle
    liip_imagine.controller:
        class: '%liip_imagine.controller.class%'
        arguments:
            - '@liip_imagine.data.manager'
            - '@liip_imagine.filter.manager'
            - '@liip_imagine.cache.manager'
            - '@liip_imagine.cache.signer'
            - '@logger'
        calls:
            - ['setContainer', ['@service_container']]
    # this service is an override of the definition in the LiipImagineBundle
    liip_imagine.cache.resolver.prototype.web_path:
        class: '%liip_imagine.cache.resolver.web_path.class%'
        arguments:
            - '@filesystem'
            - '@router.request_context'
            - ~ # will be injected by WebPathResolverFactory
            - ~ # will be injected by WebPathResolverFactory

    liip_imagine.filter.loader.format:
        class: 'Genj\ThumbnailBundle\Imagine\Filter\Loader\FormatFilterLoader'
        tags:
            - { name: 'liip_imagine.filter.loader', loader: 'format' }

    genj_thumbnail.twig.thumbnail_extension:
        class: 'Genj\ThumbnailBundle\Twig\ThumbnailExtension'
        arguments:
            - '@liip_imagine.cache.manager'
            - '@logger'
        tags:
            - { name: 'twig.extension' }

    genj_thumbnail.listener.thumbnail_cleaner:
        class: 'Genj\ThumbnailBundle\EventSubscriber\ThumbnailCleaner'
        arguments:
            - '@vich_uploader.metadata_driver.annotation'
            - '@liip_imagine.filter.configuration'
            - '@liip_imagine.cache.manager'
            - '@event_dispatcher'
        tags:
            - { name: 'doctrine.event_subscriber' }

    genj_thumbnail.subscriber.cloudflare_purger:
        class: 'Genj\ThumbnailBundle\EventSubscriber\CloudflarePurger'
        arguments:
            - '%genj_thumbnail.cloudflare%'
            - '%cdn_domain%'
            - '@vich_uploader.templating.helper.uploader_helper'
            - '@logger'
        tags:
            - { name: 'kernel.event_subscriber' }

    genj_thumbnail.cache.resolver.prototype.localAndCdnResolver:
        class: 'Genj\ThumbnailBundle\Imagine\Cache\Resolver\LocalAndCdnResolver'
        arguments:
            - '@filesystem'
            - '@router.request_context'
            - ~ # webRootDir, injected
            - ~ # cachePrefix, injected
            - ~ # useCdn, injected
            - ~ # cdn, injected
        tags: ~ # injected
